### ISSUE TITLE
Windows / Vagrant Up / network interface

### ISSUE THREAD

**Issue by mikemeier** [dominikzogg/vagrant-php#14] opened 2015-07-30 20:27 UTC
D:\Projects\test\vagrant-php>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'boxcutter/debian80' is up to date...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #4",
"--ip", "172.28.128.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name co
uld not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWr
ap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).ra
w(), hif.asOutParam())" at line 204 of file VBoxManageHostonly.cpp

**Comment by dominikzogg** [comment] 2015-07-31 04:20
looks like this one: https://github.com/mitchellh/vagrant/issues/4970

Can you try this one: https://github.com/dominikzogg/vagrant-php#dhcp-private_network-fails
(do not forget to add .exe)

**Comment by mikemeier** [comment] 2015-08-01 09:06
D:\Programme\Virtualbox>VBoxManage.exe dhcpserver remove --netname HostInterface
Networking-vboxnet0
VBoxManage.exe: error: DHCP server does not exist

**Comment by dominikzogg** [comment] 2015-08-01 09:09
Please try it with 1 instead if 0 at the end of the command.

**Comment by mikemeier** [comment] 2015-08-01 09:14
D:\Programme\Virtualbox>VBoxManage.exe dhcpserver remove --netname HostInterface
Networking-vboxnet1
VBoxManage.exe: error: DHCP server does not exist

**Comment by dominikzogg** [comment] 2015-08-01 09:18
Could it be you, that you had installed virtualbox some time ago and
updated or reinstalled it?

Old versions of the virtualbox drivers could be the problem.

https://github.com/mitchellh/vagrant/issues/4970#issuecomment-121793159

**Comment by mikemeier** [comment] 2015-08-01 09:22
I installed VB 2 days ago / I used this link: VirtualBox 5.0 for Windows hosts  x86/amd64

**Comment by dominikzogg** [comment] 2015-08-01 09:25
hmm, to be honest, god no idea, at the moment.
i would suggest to uninstall and reinstall virtualbox again

**Comment by dominikzogg** [comment] 2015-08-01 09:32
this could help: https://github.com/mitchellh/vagrant/issues/2392#issuecomment-26936014

**Comment by dominikzogg** [comment] 2015-08-01 09:35
The private network is the problem, but without the private network you can't get nfs running, which means very bad performance using projects like symfony

**Comment by Serphiroth** [comment] 2015-08-01 19:47
Have the same problem here, after i run `vagrant up` i got:

    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Clearing any previously set network interfaces...
    There was an error while executing `VBoxManage`, a CLI used by Vagrant
    for controlling VirtualBox. The command and stderr is shown below.

    Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #25", "--ip", "192.168.33.1", "--netmask", "255.255.255.0"]

    Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
    VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
    VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 204 of file VBoxManageHostonly.cpp

i'm running Windows 10, VirtualBox 5 and Vagrant 1.7.4

**Comment by dominikzogg** [comment] 2015-08-02 07:41
@mikemeier @Serphiroth do you tried the suggestions within the issue on vagrant itself? https://github.com/mitchellh/vagrant/issues/4970#issuecomment-66989504

I am sure its cause private network, but i can't remove this functionality from the Vagrantfile without remove nfs and nfs-bindfs sharetyp.

**Comment by dominikzogg** [comment] 2015-08-02 07:44
There is also an issue, thats seems close to this on virtualbox itself: https://www.virtualbox.org/ticket/12182

**Comment by dominikzogg** [comment] 2015-08-02 08:59
@mikemeier @Serphiroth 

This are the virtualbox settings i got on a linux host, could be this will help:

File -> Settings -> Network

Swicht to: Tab Host-Only Network
Add new
Change Host-Only Network

Tab Adapter
 * IPv4-Address: 172.28.128.1
 * IPv4-Netmask: 255.255.255.0
 * IPv6-Address: fe80:0000:0000:0000:0800:27ff:fe00:0000
 * IPv6-Netmask-Length: 64

Tab DHCP-Server
 * Server-Address: 172.28.128.2
 * Server-Mask: 255.255.255.0
 * Smallest-Address: 172.28.128.3
 * Largest-Address: 172.28.128.254

**Comment by dominikzogg** [comment] 2015-08-05 18:16
@mikemeier any news on this? did my suggestion help?

**Comment by dominikzogg** [comment] 2015-08-17 04:39
@Serphiroth any news on this? did my suggestion help?

**Comment by Serphiroth** [comment] 2015-08-17 17:09
@dominikzogg Thank you for your replay !
i solved it :

1- I run VBox-Win10-fix-14040.exe as Admin (See this Discussion : https://www.virtualbox.org/ticket/14040)

2- Run the VirtualBox.exe as Admin + Compatibility with Windows 7

3- And Vagrant up :)

**Comment by dominikzogg** [comment] 2015-08-17 18:42
@Serphiroth thanks for the feedback!
@mikemeier can you try this too?

**Comment by mikemeier** [comment] 2015-08-18 09:07
I'll try today @dominikzogg

**Comment by dominikzogg** [comment] 2015-09-09 19:07
@mikemeier any news?

**Comment by mikemeier** [comment] 2015-09-14 08:09
My PC crashed and now I've got Win10. Will try to install it again plain and post the feedback.

**Comment by dominikzogg** [comment] 2015-09-14 09:04
@mikemeier i hope my setup was not the reason for the crash ;-)

**Comment by dominikzogg** [comment] 2015-09-29 19:39
@mikemeier did you found the time to test it?

**Comment by mikemeier** [comment] 2015-09-29 20:45
https://github.com/dominikzogg/vagrant-php/blob/v1-ubuntu/doc/installation/windows.md --> install GIT with SSH Download Link points to Vagrant download, which one should I use?

**Comment by dominikzogg** [comment] 2015-09-30 06:01
@mikemeier had a error within markdown, should be fixed

**Comment by mikemeier** [comment] 2015-09-30 19:22
Win10 with standard setup works. Only thing a had to do: Add the SSH Client D:\Programme\Git\usr\bin to your Path Environment variable so vagrant ssh would work.

**Comment by dominikzogg** [comment] 2015-09-30 19:27
@mikemeier thank you for your feedback, can you explain how you made this? so i could add to the documentation

**Comment by mikemeier** [comment] 2015-09-30 19:41
Aaand I needed to execute manually "vagrant hostmanager" so that the project is managed in the hosts file with the correct ip

**Comment by mikemeier** [comment] 2015-09-30 19:42
Add Environment-Variable in Win10:
* Win Button
* Search for Systemproperties
* Environment-Variables
* System-Variables
* Edit the Variable 'Path': Add ';D:\Programme\Git\usr\bin'

**Comment by dominikzogg** [comment] 2015-10-01 05:28
@mikemeier thank you for the explanation

Well the problem is, that a normal user within windows (and any other OS) has not the permission to update the hosts file, which means if you run vagrant from a admin cmd it should work.

 * Win Button
 * cmd (press ctrl+shift+enter)

**Comment by mikemeier** [comment] 2015-10-01 07:46
Actually as I started 'vagrant hostmanager' on a non admin console, it asked me for admin permissions for editing the hosts file. so that worked very well. I just had to start it on my own.

**Comment by dominikzogg** [comment] 2015-10-04 13:05
@mikemeier at the moment i got a native windows for testing, i try to enhance this, thank your for your feedback

**Comment by Tjolof** [comment] 2015-10-08 11:55
I solved this problem by installing VB-guest addition.

vagrant plugin install vagrant-vbguest
vagrant reload
vagrant up

And then it worked.

**Comment by dominikzogg** [comment] 2015-10-09 05:40
@mikemeier @Tjolof running bash.exe comming from git (i have to enhance the documentation) as admin works like a charm (windows 10)

But while tesing, i find out, there are performance problems on write operations using winnfs https://github.com/dominikzogg/vagrant-php/issues/39, i will compare this vs the vboxfs, probably i have to suggests to use this one for heavy write operations as composer install

**Closed** 2015-10-11 14:05 UTC
Labels: bug
